;= @echo off
;= rem Call DOSKEY and use this file as the macrofile
;= %SystemRoot%\system32\doskey /listsize=1000 /macrofile=%0%
;= rem In batch mode, jump to the end of the file
;= goto:eof
;= Add aliases below here
e.=explorer .
gl=git log --oneline --all --graph --decorate  $*
ls=ls --show-control-chars -F --color $*
history=cat "%CMDER_ROOT%\config\.history"
unalias=alias /d $1
cmderr=cd /d "%CMDER_ROOT%"
;=
;= Custom
go=git remote update $t git branch -vv
gp=git pull
gs=git status
ga=git add --all
gg=git commit
gc=git checkout -- .
dev=npm run dev
~1=~0,-1  
cpt=cd $b clip  
tgcl=git clone git@thorne:$*  
tgit=git config user.email tomica.trncic@gmail.com $t git config user.name Thom Thorne  
ngit=git config user.email ttrncic@autozubak.hr $t git config user.name tomica  
ngcl=git clone git@neo:$*  
